name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - washing-machine

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Enable corepack for Yarn Berry
        run: corepack enable

      - name: Install dependencies
        run: cd ui && yarn install

      - name: Build
        run: cd ui && yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/dist
          publish_branch: gh-pages
